// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: catalog/proto/catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdjustmentReason int32

const (
	AdjustmentReason_ADJUSTMENT_REASON_UNSPECIFIED AdjustmentReason = 0
	AdjustmentReason_ADJUSTMENT_REASON_RESTOCK     AdjustmentReason = 1
	AdjustmentReason_ADJUSTMENT_REASON_SPOILAGE    AdjustmentReason = 2
	AdjustmentReason_ADJUSTMENT_REASON_CORRECTION  AdjustmentReason = 3
	AdjustmentReason_ADJUSTMENT_REASON_RETURN      AdjustmentReason = 4
)

// Enum value maps for AdjustmentReason.
var (
	AdjustmentReason_name = map[int32]string{
		0: "ADJUSTMENT_REASON_UNSPECIFIED",
		1: "ADJUSTMENT_REASON_RESTOCK",
		2: "ADJUSTMENT_REASON_SPOILAGE",
		3: "ADJUSTMENT_REASON_CORRECTION",
		4: "ADJUSTMENT_REASON_RETURN",
	}
	AdjustmentReason_value = map[string]int32{
		"ADJUSTMENT_REASON_UNSPECIFIED": 0,
		"ADJUSTMENT_REASON_RESTOCK":     1,
		"ADJUSTMENT_REASON_SPOILAGE":    2,
		"ADJUSTMENT_REASON_CORRECTION":  3,
		"ADJUSTMENT_REASON_RETURN":      4,
	}
)

func (x AdjustmentReason) Enum() *AdjustmentReason {
	p := new(AdjustmentReason)
	*p = x
	return p
}

func (x AdjustmentReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdjustmentReason) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_proto_catalog_proto_enumTypes[0].Descriptor()
}

func (AdjustmentReason) Type() protoreflect.EnumType {
	return &file_catalog_proto_catalog_proto_enumTypes[0]
}

func (x AdjustmentReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdjustmentReason.Descriptor instead.
func (AdjustmentReason) EnumDescriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{0}
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`      // selling price in minor units
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"` // e.g. "UGX"
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Active        bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	InitialStock  int64                  `protobuf:"varint,8,opt,name=initial_stock,json=initialStock,proto3" json:"initial_stock,omitempty"` // merge payoff: seeds the StockItem in the same call
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProductRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateProductRequest) GetInitialStock() int64 {
	if x != nil {
		return x.InitialStock
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"` // scope to one vendor's catalog
	Featured      bool                   `protobuf:"varint,2,opt,name=featured,proto3" json:"featured,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *ListProductsRequest) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"` // "" if single-location
	OnHand        int64                  `protobuf:"varint,4,opt,name=on_hand,json=onHand,proto3" json:"on_hand,omitempty"`
	Reserved      int64                  `protobuf:"varint,5,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Available     int64                  `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"` // derived: on_hand - reserved
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`      // optimistic-concurrency token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *StockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockItem) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *StockItem) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *StockItem) GetOnHand() int64 {
	if x != nil {
		return x.OnHand
	}
	return 0
}

func (x *StockItem) GetReserved() int64 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *StockItem) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *StockItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AvailabilityQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityQuery) Reset() {
	*x = AvailabilityQuery{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityQuery) ProtoMessage() {}

func (x *AvailabilityQuery) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityQuery.ProtoReflect.Descriptor instead.
func (*AvailabilityQuery) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *AvailabilityQuery) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AvailabilityQuery) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *AvailabilityQuery) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AvailabilityQuery   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *CheckAvailabilityRequest) GetItems() []*AvailabilityQuery {
	if x != nil {
		return x.Items
	}
	return nil
}

type AvailabilityResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Available     int64                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Sufficient    bool                   `protobuf:"varint,3,opt,name=sufficient,proto3" json:"sufficient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityResult) Reset() {
	*x = AvailabilityResult{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityResult) ProtoMessage() {}

func (x *AvailabilityResult) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityResult.ProtoReflect.Descriptor instead.
func (*AvailabilityResult) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *AvailabilityResult) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AvailabilityResult) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *AvailabilityResult) GetSufficient() bool {
	if x != nil {
		return x.Sufficient
	}
	return false
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AvailabilityResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *CheckAvailabilityResponse) GetResults() []*AvailabilityResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type AdjustStockRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProductId  string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	// Types that are valid to be assigned to Change:
	//
	//	*AdjustStockRequest_Delta
	//	*AdjustStockRequest_SetTo
	Change          isAdjustStockRequest_Change `protobuf_oneof:"change"`
	Reason          AdjustmentReason            `protobuf:"varint,5,opt,name=reason,proto3,enum=grocery.catalog.AdjustmentReason" json:"reason,omitempty"`
	ExpectedVersion string                      `protobuf:"bytes,6,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // optional concurrency check
	IdempotencyKey  string                      `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdjustStockRequest) Reset() {
	*x = AdjustStockRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustStockRequest) ProtoMessage() {}

func (x *AdjustStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustStockRequest.ProtoReflect.Descriptor instead.
func (*AdjustStockRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *AdjustStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AdjustStockRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *AdjustStockRequest) GetChange() isAdjustStockRequest_Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *AdjustStockRequest) GetDelta() int64 {
	if x != nil {
		if x, ok := x.Change.(*AdjustStockRequest_Delta); ok {
			return x.Delta
		}
	}
	return 0
}

func (x *AdjustStockRequest) GetSetTo() int64 {
	if x != nil {
		if x, ok := x.Change.(*AdjustStockRequest_SetTo); ok {
			return x.SetTo
		}
	}
	return 0
}

func (x *AdjustStockRequest) GetReason() AdjustmentReason {
	if x != nil {
		return x.Reason
	}
	return AdjustmentReason_ADJUSTMENT_REASON_UNSPECIFIED
}

func (x *AdjustStockRequest) GetExpectedVersion() string {
	if x != nil {
		return x.ExpectedVersion
	}
	return ""
}

func (x *AdjustStockRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type isAdjustStockRequest_Change interface {
	isAdjustStockRequest_Change()
}

type AdjustStockRequest_Delta struct {
	Delta int64 `protobuf:"varint,3,opt,name=delta,proto3,oneof"` // +restock / -spoilage
}

type AdjustStockRequest_SetTo struct {
	SetTo int64 `protobuf:"varint,4,opt,name=set_to,json=setTo,proto3,oneof"` // physical recount
}

func (*AdjustStockRequest_Delta) isAdjustStockRequest_Change() {}

func (*AdjustStockRequest_SetTo) isAdjustStockRequest_Change() {}

type ReserveItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItem) Reset() {
	*x = ReserveItem{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItem) ProtoMessage() {}

func (x *ReserveItem) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItem.ProtoReflect.Descriptor instead.
func (*ReserveItem) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *ReserveItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReserveItem) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ReserveItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items          []*ReserveItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Ttl            *durationpb.Duration   `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // hold auto-expires if not committed
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *ReserveRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveRequest) GetItems() []*ReserveItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *ReserveRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Held          bool                   `protobuf:"varint,2,opt,name=held,proto3" json:"held,omitempty"`
	Shortfalls    []*AvailabilityResult  `protobuf:"bytes,3,rep,name=shortfalls,proto3" json:"shortfalls,omitempty"` // set when held = false
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *ReserveResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveResponse) GetHeld() bool {
	if x != nil {
		return x.Held
	}
	return false
}

func (x *ReserveResponse) GetShortfalls() []*AvailabilityResult {
	if x != nil {
		return x.Shortfalls
	}
	return nil
}

func (x *ReserveResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CommitReservationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationId  string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitReservationRequest) Reset() {
	*x = CommitReservationRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReservationRequest) ProtoMessage() {}

func (x *CommitReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReservationRequest.ProtoReflect.Descriptor instead.
func (*CommitReservationRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *CommitReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CommitReservationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CommitReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     bool                   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReservationResponse) Reset() {
	*x = CommitReservationResponse{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReservationResponse) ProtoMessage() {}

func (x *CommitReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReservationResponse.ProtoReflect.Descriptor instead.
func (*CommitReservationResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *CommitReservationResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // "cancelled", "payment_failed", "expired"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseReservationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_catalog_proto_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *ReleaseReservationResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

var File_catalog_proto_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bcatalog/proto/catalog.proto\x12\x0fgrocery.catalog\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xae\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xfd\x01\n" +
	"\x14CreateProductRequest\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12#\n" +
	"\rinitial_stock\x18\b \x01(\x03R\finitialStock\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\xb5\x01\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"\x8e\x01\n" +
	"\x13ListProductsRequest\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x1a\n" +
	"\bfeatured\x18\x02 \x01(\bR\bfeatured\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"t\n" +
	"\x14ListProductsResponse\x124\n" +
	"\bproducts\x18\x01 \x03(\v2\x18.grocery.catalog.ProductR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd9\x01\n" +
	"\tStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x17\n" +
	"\aon_hand\x18\x04 \x01(\x03R\x06onHand\x12\x1a\n" +
	"\breserved\x18\x05 \x01(\x03R\breserved\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\x03R\tavailable\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"o\n" +
	"\x11AvailabilityQuery\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"T\n" +
	"\x18CheckAvailabilityRequest\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".grocery.catalog.AvailabilityQueryR\x05items\"q\n" +
	"\x12AvailabilityResult\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x03R\tavailable\x12\x1e\n" +
	"\n" +
	"sufficient\x18\x03 \x01(\bR\n" +
	"sufficient\"Z\n" +
	"\x19CheckAvailabilityResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.grocery.catalog.AvailabilityResultR\aresults\"\x9e\x02\n" +
	"\x12AdjustStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x16\n" +
	"\x05delta\x18\x03 \x01(\x03H\x00R\x05delta\x12\x17\n" +
	"\x06set_to\x18\x04 \x01(\x03H\x00R\x05setTo\x129\n" +
	"\x06reason\x18\x05 \x01(\x0e2!.grocery.catalog.AdjustmentReasonR\x06reason\x12)\n" +
	"\x10expected_version\x18\x06 \x01(\tR\x0fexpectedVersion\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKeyB\b\n" +
	"\x06change\"i\n" +
	"\vReserveItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"\xb5\x01\n" +
	"\x0eReserveRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x122\n" +
	"\x05items\x18\x02 \x03(\v2\x1c.grocery.catalog.ReserveItemR\x05items\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\xcc\x01\n" +
	"\x0fReserveResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x12\n" +
	"\x04held\x18\x02 \x01(\bR\x04held\x12C\n" +
	"\n" +
	"shortfalls\x18\x03 \x03(\v2#.grocery.catalog.AvailabilityResultR\n" +
	"shortfalls\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"j\n" +
	"\x18CommitReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"9\n" +
	"\x19CommitReservationResponse\x12\x1c\n" +
	"\tcommitted\x18\x01 \x01(\bR\tcommitted\"Z\n" +
	"\x19ReleaseReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"8\n" +
	"\x1aReleaseReservationResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased*\xb4\x01\n" +
	"\x10AdjustmentReason\x12!\n" +
	"\x1dADJUSTMENT_REASON_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ADJUSTMENT_REASON_RESTOCK\x10\x01\x12\x1e\n" +
	"\x1aADJUSTMENT_REASON_SPOILAGE\x10\x02\x12 \n" +
	"\x1cADJUSTMENT_REASON_CORRECTION\x10\x03\x12\x1c\n" +
	"\x18ADJUSTMENT_REASON_RETURN\x10\x042\xc2\x06\n" +
	"\x0eCatalogService\x12P\n" +
	"\rCreateProduct\x12%.grocery.catalog.CreateProductRequest\x1a\x18.grocery.catalog.Product\x12J\n" +
	"\n" +
	"GetProduct\x12\".grocery.catalog.GetProductRequest\x1a\x18.grocery.catalog.Product\x12P\n" +
	"\rUpdateProduct\x12%.grocery.catalog.UpdateProductRequest\x1a\x18.grocery.catalog.Product\x12[\n" +
	"\fListProducts\x12$.grocery.catalog.ListProductsRequest\x1a%.grocery.catalog.ListProductsResponse\x12j\n" +
	"\x11CheckAvailability\x12).grocery.catalog.CheckAvailabilityRequest\x1a*.grocery.catalog.CheckAvailabilityResponse\x12N\n" +
	"\vAdjustStock\x12#.grocery.catalog.AdjustStockRequest\x1a\x1a.grocery.catalog.StockItem\x12L\n" +
	"\aReserve\x12\x1f.grocery.catalog.ReserveRequest\x1a .grocery.catalog.ReserveResponse\x12j\n" +
	"\x11CommitReservation\x12).grocery.catalog.CommitReservationRequest\x1a*.grocery.catalog.CommitReservationResponse\x12m\n" +
	"\x12ReleaseReservation\x12*.grocery.catalog.ReleaseReservationRequest\x1a+.grocery.catalog.ReleaseReservationResponseB\x1dZ\x1bthugcorp.io/grocery/catalogb\x06proto3"

var (
	file_catalog_proto_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_catalog_proto_rawDescData []byte
)

func file_catalog_proto_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_catalog_proto_rawDesc), len(file_catalog_proto_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_catalog_proto_rawDescData
}

var file_catalog_proto_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalog_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_catalog_proto_catalog_proto_goTypes = []any{
	(AdjustmentReason)(0),              // 0: grocery.catalog.AdjustmentReason
	(*Product)(nil),                    // 1: grocery.catalog.Product
	(*CreateProductRequest)(nil),       // 2: grocery.catalog.CreateProductRequest
	(*GetProductRequest)(nil),          // 3: grocery.catalog.GetProductRequest
	(*UpdateProductRequest)(nil),       // 4: grocery.catalog.UpdateProductRequest
	(*ListProductsRequest)(nil),        // 5: grocery.catalog.ListProductsRequest
	(*ListProductsResponse)(nil),       // 6: grocery.catalog.ListProductsResponse
	(*StockItem)(nil),                  // 7: grocery.catalog.StockItem
	(*AvailabilityQuery)(nil),          // 8: grocery.catalog.AvailabilityQuery
	(*CheckAvailabilityRequest)(nil),   // 9: grocery.catalog.CheckAvailabilityRequest
	(*AvailabilityResult)(nil),         // 10: grocery.catalog.AvailabilityResult
	(*CheckAvailabilityResponse)(nil),  // 11: grocery.catalog.CheckAvailabilityResponse
	(*AdjustStockRequest)(nil),         // 12: grocery.catalog.AdjustStockRequest
	(*ReserveItem)(nil),                // 13: grocery.catalog.ReserveItem
	(*ReserveRequest)(nil),             // 14: grocery.catalog.ReserveRequest
	(*ReserveResponse)(nil),            // 15: grocery.catalog.ReserveResponse
	(*CommitReservationRequest)(nil),   // 16: grocery.catalog.CommitReservationRequest
	(*CommitReservationResponse)(nil),  // 17: grocery.catalog.CommitReservationResponse
	(*ReleaseReservationRequest)(nil),  // 18: grocery.catalog.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil), // 19: grocery.catalog.ReleaseReservationResponse
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 21: google.protobuf.Duration
}
var file_catalog_proto_catalog_proto_depIdxs = []int32{
	20, // 0: grocery.catalog.Product.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: grocery.catalog.ListProductsResponse.products:type_name -> grocery.catalog.Product
	8,  // 2: grocery.catalog.CheckAvailabilityRequest.items:type_name -> grocery.catalog.AvailabilityQuery
	10, // 3: grocery.catalog.CheckAvailabilityResponse.results:type_name -> grocery.catalog.AvailabilityResult
	0,  // 4: grocery.catalog.AdjustStockRequest.reason:type_name -> grocery.catalog.AdjustmentReason
	13, // 5: grocery.catalog.ReserveRequest.items:type_name -> grocery.catalog.ReserveItem
	21, // 6: grocery.catalog.ReserveRequest.ttl:type_name -> google.protobuf.Duration
	10, // 7: grocery.catalog.ReserveResponse.shortfalls:type_name -> grocery.catalog.AvailabilityResult
	20, // 8: grocery.catalog.ReserveResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 9: grocery.catalog.CatalogService.CreateProduct:input_type -> grocery.catalog.CreateProductRequest
	3,  // 10: grocery.catalog.CatalogService.GetProduct:input_type -> grocery.catalog.GetProductRequest
	4,  // 11: grocery.catalog.CatalogService.UpdateProduct:input_type -> grocery.catalog.UpdateProductRequest
	5,  // 12: grocery.catalog.CatalogService.ListProducts:input_type -> grocery.catalog.ListProductsRequest
	9,  // 13: grocery.catalog.CatalogService.CheckAvailability:input_type -> grocery.catalog.CheckAvailabilityRequest
	12, // 14: grocery.catalog.CatalogService.AdjustStock:input_type -> grocery.catalog.AdjustStockRequest
	14, // 15: grocery.catalog.CatalogService.Reserve:input_type -> grocery.catalog.ReserveRequest
	16, // 16: grocery.catalog.CatalogService.CommitReservation:input_type -> grocery.catalog.CommitReservationRequest
	18, // 17: grocery.catalog.CatalogService.ReleaseReservation:input_type -> grocery.catalog.ReleaseReservationRequest
	1,  // 18: grocery.catalog.CatalogService.CreateProduct:output_type -> grocery.catalog.Product
	1,  // 19: grocery.catalog.CatalogService.GetProduct:output_type -> grocery.catalog.Product
	1,  // 20: grocery.catalog.CatalogService.UpdateProduct:output_type -> grocery.catalog.Product
	6,  // 21: grocery.catalog.CatalogService.ListProducts:output_type -> grocery.catalog.ListProductsResponse
	11, // 22: grocery.catalog.CatalogService.CheckAvailability:output_type -> grocery.catalog.CheckAvailabilityResponse
	7,  // 23: grocery.catalog.CatalogService.AdjustStock:output_type -> grocery.catalog.StockItem
	15, // 24: grocery.catalog.CatalogService.Reserve:output_type -> grocery.catalog.ReserveResponse
	17, // 25: grocery.catalog.CatalogService.CommitReservation:output_type -> grocery.catalog.CommitReservationResponse
	19, // 26: grocery.catalog.CatalogService.ReleaseReservation:output_type -> grocery.catalog.ReleaseReservationResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_catalog_proto_catalog_proto_init() }
func file_catalog_proto_catalog_proto_init() {
	if File_catalog_proto_catalog_proto != nil {
		return
	}
	file_catalog_proto_catalog_proto_msgTypes[11].OneofWrappers = []any{
		(*AdjustStockRequest_Delta)(nil),
		(*AdjustStockRequest_SetTo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_catalog_proto_rawDesc), len(file_catalog_proto_catalog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_catalog_proto_depIdxs,
		EnumInfos:         file_catalog_proto_catalog_proto_enumTypes,
		MessageInfos:      file_catalog_proto_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto_catalog_proto = out.File
	file_catalog_proto_catalog_proto_goTypes = nil
	file_catalog_proto_catalog_proto_depIdxs = nil
}
