// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ordering/proto/ordering.proto

package ordering

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING_PAYMENT  OrderStatus = 1
	OrderStatus_ORDER_STATUS_CONFIRMED        OrderStatus = 2
	OrderStatus_ORDER_STATUS_PREPARING        OrderStatus = 3
	OrderStatus_ORDER_STATUS_OUT_FOR_DELIVERY OrderStatus = 4
	OrderStatus_ORDER_STATUS_DELIVERED        OrderStatus = 5
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 6
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING_PAYMENT",
		2: "ORDER_STATUS_CONFIRMED",
		3: "ORDER_STATUS_PREPARING",
		4: "ORDER_STATUS_OUT_FOR_DELIVERY",
		5: "ORDER_STATUS_DELIVERED",
		6: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_PENDING_PAYMENT":  1,
		"ORDER_STATUS_CONFIRMED":        2,
		"ORDER_STATUS_PREPARING":        3,
		"ORDER_STATUS_OUT_FOR_DELIVERY": 4,
		"ORDER_STATUS_DELIVERED":        5,
		"ORDER_STATUS_CANCELLED":        6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ordering_proto_ordering_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_ordering_proto_ordering_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{0}
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      int64                  `protobuf:"varint,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"` // minor units, computed
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{0}
}

func (x *Cart) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *Cart) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                             // cached for display
	UnitPrice     int64                  `protobuf:"varint,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"` // cached for display; live catalog price is authoritative
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{1}
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CartItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItem) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CartItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{3}
}

func (x *AddItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddItemRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"` // 0 removes the line
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateItemRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{6}
}

func (x *ClearCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClearCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cleared       bool                   `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResponse) Reset() {
	*x = ClearCartResponse{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResponse) ProtoMessage() {}

func (x *ClearCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResponse.ProtoReflect.Descriptor instead.
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{7}
}

func (x *ClearCartResponse) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

type Order struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items  []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"` // each line carries business_id; per-vendor
	// sub-orders can be layered on later if needed
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=grocery.ordering.OrderStatus" json:"status,omitempty"`
	Total         int64                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"` // minor units
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentId     string                 `protobuf:"bytes,7,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // set once payment is initiated
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{8}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// name + price are SNAPSHOTTED at checkout, so the order stays a correct record
// even after the catalog price changes.
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	BusinessId    string                 `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	UnitPrice     int64                  `protobuf:"varint,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"` // price at time of sale
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LineTotal     int64                  `protobuf:"varint,6,opt,name=line_total,json=lineTotal,proto3" json:"line_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{9}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetLineTotal() int64 {
	if x != nil {
		return x.LineTotal
	}
	return 0
}

type CheckoutRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // whose cart to convert
	DeliveryAddress string                 `protobuf:"bytes,2,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`    // e.g. "mtn_momo", "airtel_money"
	IdempotencyKey  string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // avoid double-ordering on retry
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{10}
}

func (x *CheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckoutRequest) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *CheckoutRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CheckoutRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by customer OR by vendor (a vendor's incoming orders).
	//
	// Types that are valid to be assigned to Filter:
	//
	//	*ListOrdersRequest_UserId
	//	*ListOrdersRequest_BusinessId
	Filter        isListOrdersRequest_Filter `protobuf_oneof:"filter"`
	Status        OrderStatus                `protobuf:"varint,3,opt,name=status,proto3,enum=grocery.ordering.OrderStatus" json:"status,omitempty"` // optional
	PageSize      int32                      `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                     `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{12}
}

func (x *ListOrdersRequest) GetFilter() isListOrdersRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		if x, ok := x.Filter.(*ListOrdersRequest_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

func (x *ListOrdersRequest) GetBusinessId() string {
	if x != nil {
		if x, ok := x.Filter.(*ListOrdersRequest_BusinessId); ok {
			return x.BusinessId
		}
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type isListOrdersRequest_Filter interface {
	isListOrdersRequest_Filter()
}

type ListOrdersRequest_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type ListOrdersRequest_BusinessId struct {
	BusinessId string `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3,oneof"`
}

func (*ListOrdersRequest_UserId) isListOrdersRequest_Filter() {}

func (*ListOrdersRequest_BusinessId) isListOrdersRequest_Filter() {}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=grocery.ordering.OrderStatus" json:"status,omitempty"` // vendor / fulfillment transitions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_ordering_proto_ordering_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_ordering_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_ordering_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

var File_ordering_proto_ordering_proto protoreflect.FileDescriptor

const file_ordering_proto_ordering_proto_rawDesc = "" +
	"\n" +
	"\x1dordering/proto/ordering.proto\x12\x10grocery.ordering\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\x04Cart\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.grocery.ordering.CartItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x03 \x01(\x03R\bsubtotal\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\x99\x01\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x03R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"d\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"g\n" +
	"\x11UpdateItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"K\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\"+\n" +
	"\x10ClearCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x11ClearCartResponse\x12\x18\n" +
	"\acleared\x18\x01 \x01(\bR\acleared\"\xa6\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x121\n" +
	"\x05items\x18\x03 \x03(\v2\x1b.grocery.ordering.OrderItemR\x05items\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.grocery.ordering.OrderStatusR\x06status\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"payment_id\x18\a \x01(\tR\tpaymentId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc8\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vbusiness_id\x18\x02 \x01(\tR\n" +
	"businessId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x03R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x1d\n" +
	"\n" +
	"line_total\x18\x06 \x01(\x03R\tlineTotal\"\xa5\x01\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10delivery_address\x18\x02 \x01(\tR\x0fdeliveryAddress\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xce\x01\n" +
	"\x11ListOrdersRequest\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x12!\n" +
	"\vbusiness_id\x18\x02 \x01(\tH\x00R\n" +
	"businessId\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.grocery.ordering.OrderStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageTokenB\b\n" +
	"\x06filter\"m\n" +
	"\x12ListOrdersResponse\x12/\n" +
	"\x06orders\x18\x01 \x03(\v2\x17.grocery.ordering.OrderR\x06orders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"l\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.grocery.ordering.OrderStatusR\x06status*\xe0\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cORDER_STATUS_PENDING_PAYMENT\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_CONFIRMED\x10\x02\x12\x1a\n" +
	"\x16ORDER_STATUS_PREPARING\x10\x03\x12!\n" +
	"\x1dORDER_STATUS_OUT_FOR_DELIVERY\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x062\xca\x05\n" +
	"\x0fOrderingService\x12C\n" +
	"\aGetCart\x12 .grocery.ordering.GetCartRequest\x1a\x16.grocery.ordering.Cart\x12C\n" +
	"\aAddItem\x12 .grocery.ordering.AddItemRequest\x1a\x16.grocery.ordering.Cart\x12I\n" +
	"\n" +
	"UpdateItem\x12#.grocery.ordering.UpdateItemRequest\x1a\x16.grocery.ordering.Cart\x12I\n" +
	"\n" +
	"RemoveItem\x12#.grocery.ordering.RemoveItemRequest\x1a\x16.grocery.ordering.Cart\x12T\n" +
	"\tClearCart\x12\".grocery.ordering.ClearCartRequest\x1a#.grocery.ordering.ClearCartResponse\x12F\n" +
	"\bCheckout\x12!.grocery.ordering.CheckoutRequest\x1a\x17.grocery.ordering.Order\x12F\n" +
	"\bGetOrder\x12!.grocery.ordering.GetOrderRequest\x1a\x17.grocery.ordering.Order\x12W\n" +
	"\n" +
	"ListOrders\x12#.grocery.ordering.ListOrdersRequest\x1a$.grocery.ordering.ListOrdersResponse\x12X\n" +
	"\x11UpdateOrderStatus\x12*.grocery.ordering.UpdateOrderStatusRequest\x1a\x17.grocery.ordering.OrderB\x1eZ\x1cthugcorp.io/grocery/orderingb\x06proto3"

var (
	file_ordering_proto_ordering_proto_rawDescOnce sync.Once
	file_ordering_proto_ordering_proto_rawDescData []byte
)

func file_ordering_proto_ordering_proto_rawDescGZIP() []byte {
	file_ordering_proto_ordering_proto_rawDescOnce.Do(func() {
		file_ordering_proto_ordering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ordering_proto_ordering_proto_rawDesc), len(file_ordering_proto_ordering_proto_rawDesc)))
	})
	return file_ordering_proto_ordering_proto_rawDescData
}

var file_ordering_proto_ordering_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ordering_proto_ordering_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ordering_proto_ordering_proto_goTypes = []any{
	(OrderStatus)(0),                 // 0: grocery.ordering.OrderStatus
	(*Cart)(nil),                     // 1: grocery.ordering.Cart
	(*CartItem)(nil),                 // 2: grocery.ordering.CartItem
	(*GetCartRequest)(nil),           // 3: grocery.ordering.GetCartRequest
	(*AddItemRequest)(nil),           // 4: grocery.ordering.AddItemRequest
	(*UpdateItemRequest)(nil),        // 5: grocery.ordering.UpdateItemRequest
	(*RemoveItemRequest)(nil),        // 6: grocery.ordering.RemoveItemRequest
	(*ClearCartRequest)(nil),         // 7: grocery.ordering.ClearCartRequest
	(*ClearCartResponse)(nil),        // 8: grocery.ordering.ClearCartResponse
	(*Order)(nil),                    // 9: grocery.ordering.Order
	(*OrderItem)(nil),                // 10: grocery.ordering.OrderItem
	(*CheckoutRequest)(nil),          // 11: grocery.ordering.CheckoutRequest
	(*GetOrderRequest)(nil),          // 12: grocery.ordering.GetOrderRequest
	(*ListOrdersRequest)(nil),        // 13: grocery.ordering.ListOrdersRequest
	(*ListOrdersResponse)(nil),       // 14: grocery.ordering.ListOrdersResponse
	(*UpdateOrderStatusRequest)(nil), // 15: grocery.ordering.UpdateOrderStatusRequest
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
}
var file_ordering_proto_ordering_proto_depIdxs = []int32{
	2,  // 0: grocery.ordering.Cart.items:type_name -> grocery.ordering.CartItem
	10, // 1: grocery.ordering.Order.items:type_name -> grocery.ordering.OrderItem
	0,  // 2: grocery.ordering.Order.status:type_name -> grocery.ordering.OrderStatus
	16, // 3: grocery.ordering.Order.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: grocery.ordering.ListOrdersRequest.status:type_name -> grocery.ordering.OrderStatus
	9,  // 5: grocery.ordering.ListOrdersResponse.orders:type_name -> grocery.ordering.Order
	0,  // 6: grocery.ordering.UpdateOrderStatusRequest.status:type_name -> grocery.ordering.OrderStatus
	3,  // 7: grocery.ordering.OrderingService.GetCart:input_type -> grocery.ordering.GetCartRequest
	4,  // 8: grocery.ordering.OrderingService.AddItem:input_type -> grocery.ordering.AddItemRequest
	5,  // 9: grocery.ordering.OrderingService.UpdateItem:input_type -> grocery.ordering.UpdateItemRequest
	6,  // 10: grocery.ordering.OrderingService.RemoveItem:input_type -> grocery.ordering.RemoveItemRequest
	7,  // 11: grocery.ordering.OrderingService.ClearCart:input_type -> grocery.ordering.ClearCartRequest
	11, // 12: grocery.ordering.OrderingService.Checkout:input_type -> grocery.ordering.CheckoutRequest
	12, // 13: grocery.ordering.OrderingService.GetOrder:input_type -> grocery.ordering.GetOrderRequest
	13, // 14: grocery.ordering.OrderingService.ListOrders:input_type -> grocery.ordering.ListOrdersRequest
	15, // 15: grocery.ordering.OrderingService.UpdateOrderStatus:input_type -> grocery.ordering.UpdateOrderStatusRequest
	1,  // 16: grocery.ordering.OrderingService.GetCart:output_type -> grocery.ordering.Cart
	1,  // 17: grocery.ordering.OrderingService.AddItem:output_type -> grocery.ordering.Cart
	1,  // 18: grocery.ordering.OrderingService.UpdateItem:output_type -> grocery.ordering.Cart
	1,  // 19: grocery.ordering.OrderingService.RemoveItem:output_type -> grocery.ordering.Cart
	8,  // 20: grocery.ordering.OrderingService.ClearCart:output_type -> grocery.ordering.ClearCartResponse
	9,  // 21: grocery.ordering.OrderingService.Checkout:output_type -> grocery.ordering.Order
	9,  // 22: grocery.ordering.OrderingService.GetOrder:output_type -> grocery.ordering.Order
	14, // 23: grocery.ordering.OrderingService.ListOrders:output_type -> grocery.ordering.ListOrdersResponse
	9,  // 24: grocery.ordering.OrderingService.UpdateOrderStatus:output_type -> grocery.ordering.Order
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ordering_proto_ordering_proto_init() }
func file_ordering_proto_ordering_proto_init() {
	if File_ordering_proto_ordering_proto != nil {
		return
	}
	file_ordering_proto_ordering_proto_msgTypes[12].OneofWrappers = []any{
		(*ListOrdersRequest_UserId)(nil),
		(*ListOrdersRequest_BusinessId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ordering_proto_ordering_proto_rawDesc), len(file_ordering_proto_ordering_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordering_proto_ordering_proto_goTypes,
		DependencyIndexes: file_ordering_proto_ordering_proto_depIdxs,
		EnumInfos:         file_ordering_proto_ordering_proto_enumTypes,
		MessageInfos:      file_ordering_proto_ordering_proto_msgTypes,
	}.Build()
	File_ordering_proto_ordering_proto = out.File
	file_ordering_proto_ordering_proto_goTypes = nil
	file_ordering_proto_ordering_proto_depIdxs = nil
}
