app:
  name: transactions-service
  environment: development
  port: 8089

postgres:
  host: localhost
  port: 5438
  user: postgres
  password: postgres
  dbname: transactions_db
  sslmode: disable

grpc:
  port: 50059

jwt:
  public_key_path: ../../secrets/jwt_public.pem
  private_key_path: ../../secrets/jwt_private.pem
  access_token_ttl: 3600

