app:
  name: cart-service
  environment: development
  port: 8083
  log_level: debug

cart:
  redis_addr: localhost:6379
  redis_password: ""
  redis_db: 0
  redis_pool_size: 10

grpc:
  port: 50054

jwt:
  private_key_path: "../../secrets/jwt_private.pem"
  public_key_path: "../../secrets/jwt_public.pem"
  access_token_ttl: 3600