app:
  name: auth-service
  environment: development
  port: 8080
  log_level: debug

sqlite:
  path: ""

grpc:
  port: 50052


easysend_sms:
  api_key: ""
  sender_id: ""

gmail:
  host: smtp.gmail.com
  port: 587
  username: ""
  password: ""

jwt:
  private_key_path: ""
  public_key_path: ""
  access_token_ttl: 3600

super_admin:
  email: ""
  password: ""
  first_name: "Super"
  last_name: "Admin"
