app:
  name: payment-service
  environment: development
  port: 8086

postgres:
  host: localhost
  port: 5437
  user: postgres
  password: yourpassword
  dbname: grocery_payments
  sslmode: disable

grpc:
  port: 50058

jwt:
  public_key_path: ../../secrets/jwt_public.pem
  private_key_path: ../../secrets/jwt_private.pem
  access_token_ttl: 3600

mtn:
  base_url: https://sandbox.momodeveloper.mtn.com
  subscription_key: your-subscription-key
  api_user: your-api-user-uuid
  api_key: your-api-key
  environment: sandbox        # sandbox or production
  payee_id: "256XXXXXXXXX"   # your MSISDN (receiving number)
