app:
  name: inventory-service
  environment: development
  port: 8084
  log_level: debug

postgres:
  host: localhost
  port: 5434
  user: postgres
  password: postgres
  dbname: inventory_db
  sslmode: disable

grpc:
  port: 50055

jwt:
  private_key_path: "../../secrets/jwt_private.pem"
  public_key_path: "../../secrets/jwt_public.pem"
  access_token_ttl: 3600