// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notifications/proto/notifications.proto

package notificationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_PUSH        Channel = 1
	Channel_CHANNEL_SMS         Channel = 2
	Channel_CHANNEL_EMAIL       Channel = 3
	Channel_CHANNEL_IN_APP      Channel = 4
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_PUSH",
		2: "CHANNEL_SMS",
		3: "CHANNEL_EMAIL",
		4: "CHANNEL_IN_APP",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_PUSH":        1,
		"CHANNEL_SMS":         2,
		"CHANNEL_EMAIL":       3,
		"CHANNEL_IN_APP":      4,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_proto_notifications_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_notifications_proto_notifications_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{0}
}

// Category drives opt-out rules: transactional messages always send;
// promotional ones respect the recipient's preferences.
type Category int32

const (
	Category_CATEGORY_UNSPECIFIED   Category = 0
	Category_CATEGORY_TRANSACTIONAL Category = 1 // order, payment, delivery updates
	Category_CATEGORY_PROMOTIONAL   Category = 2 // marketing, offers
	Category_CATEGORY_ACCOUNT       Category = 3 // security, login alerts
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_TRANSACTIONAL",
		2: "CATEGORY_PROMOTIONAL",
		3: "CATEGORY_ACCOUNT",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED":   0,
		"CATEGORY_TRANSACTIONAL": 1,
		"CATEGORY_PROMOTIONAL":   2,
		"CATEGORY_ACCOUNT":       3,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_proto_notifications_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_notifications_proto_notifications_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{1}
}

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_QUEUED      DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_SENT        DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_SUPPRESSED  DeliveryStatus = 3 // blocked by preference / opt-out
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 4
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_QUEUED",
		2: "DELIVERY_STATUS_SENT",
		3: "DELIVERY_STATUS_SUPPRESSED",
		4: "DELIVERY_STATUS_FAILED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_QUEUED":      1,
		"DELIVERY_STATUS_SENT":        2,
		"DELIVERY_STATUS_SUPPRESSED":  3,
		"DELIVERY_STATUS_FAILED":      4,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_proto_notifications_proto_enumTypes[2].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_notifications_proto_notifications_proto_enumTypes[2]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{2}
}

// Recipient is either a customer or a business (vendor). The service looks up
// stored contact details by id; the optional fields override them when needed.
type Recipient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*Recipient_UserId
	//	*Recipient_BusinessId
	Id            isRecipient_Id `protobuf_oneof:"id"`
	Email         string         `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string         `protobuf:"bytes,11,opt,name=phone,proto3" json:"phone,omitempty"` // E.164, e.g. +2567XXXXXXXX
	PushToken     string         `protobuf:"bytes,12,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Recipient) GetId() isRecipient_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Recipient) GetUserId() string {
	if x != nil {
		if x, ok := x.Id.(*Recipient_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

func (x *Recipient) GetBusinessId() string {
	if x != nil {
		if x, ok := x.Id.(*Recipient_BusinessId); ok {
			return x.BusinessId
		}
	}
	return ""
}

func (x *Recipient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Recipient) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Recipient) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

type isRecipient_Id interface {
	isRecipient_Id()
}

type Recipient_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type Recipient_BusinessId struct {
	BusinessId string `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3,oneof"`
}

func (*Recipient_UserId) isRecipient_Id() {}

func (*Recipient_BusinessId) isRecipient_Id() {}

type SendRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Recipient *Recipient             `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Template defines the copy per channel; variables fill the placeholders.
	// Keeps message wording out of the calling service.
	TemplateId string            `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`                                                       // e.g. "order_confirmed"
	Variables  map[string]string `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. {"order_id": "1234", "total": "45000"}
	Category   Category          `protobuf:"varint,4,opt,name=category,proto3,enum=notifications.v1.Category" json:"category,omitempty"`
	// Optional: restrict to specific channels. Empty = the template's defaults,
	// intersected with the recipient's preferences.
	Channels []Channel `protobuf:"varint,5,rep,packed,name=channels,proto3,enum=notifications.v1.Channel" json:"channels,omitempty"`
	// Dedupe key so retries (or duplicate events) don't double-send.
	IdempotencyKey string `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *SendRequest) GetRecipient() *Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *SendRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *SendRequest) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *SendRequest) GetChannels() []Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *SendRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SendResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// One Send can fan out to several channels, so report each separately.
	Results       []*ChannelResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *SendResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendResponse) GetResults() []*ChannelResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ChannelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=notifications.v1.Channel" json:"channel,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=notifications.v1.DeliveryStatus" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"` // failure reason, provider message id, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResult) Reset() {
	*x = ChannelResult{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResult) ProtoMessage() {}

func (x *ChannelResult) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResult.ProtoReflect.Descriptor instead.
func (*ChannelResult) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelResult) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ChannelResult) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *ChannelResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Notification struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body      string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Category  Category               `protobuf:"varint,4,opt,name=category,proto3,enum=notifications.v1.Category" json:"category,omitempty"`
	Read      bool                   `protobuf:"varint,5,opt,name=read,proto3" json:"read,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Deep-link payload for the client, e.g. {"screen": "order", "order_id": "1234"}.
	Data          map[string]string `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // opaque cursor from a previous response
	UnreadOnly    bool                   `protobuf:"varint,4,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotificationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type MarkReadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationIds []string               `protobuf:"bytes,2,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"` // empty = mark everything read
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkReadRequest) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{8}
}

func (x *MarkReadResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{9}
}

func (x *GetUnreadCountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{10}
}

func (x *GetUnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ChannelPreference struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Category        Category               `protobuf:"varint,1,opt,name=category,proto3,enum=notifications.v1.Category" json:"category,omitempty"`
	EnabledChannels []Channel              `protobuf:"varint,2,rep,packed,name=enabled_channels,json=enabledChannels,proto3,enum=notifications.v1.Channel" json:"enabled_channels,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelPreference) Reset() {
	*x = ChannelPreference{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPreference) ProtoMessage() {}

func (x *ChannelPreference) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPreference.ProtoReflect.Descriptor instead.
func (*ChannelPreference) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelPreference) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *ChannelPreference) GetEnabledChannels() []Channel {
	if x != nil {
		return x.EnabledChannels
	}
	return nil
}

type NotificationPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   []*ChannelPreference   `protobuf:"bytes,2,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{12}
}

func (x *NotificationPreferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationPreferences) GetPreferences() []*ChannelPreference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{13}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdatePreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   []*ChannelPreference   `protobuf:"bytes,2,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_notifications_proto_notifications_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_notifications_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_notifications_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetPreferences() []*ChannelPreference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

var File_notifications_proto_notifications_proto protoreflect.FileDescriptor

const file_notifications_proto_notifications_proto_rawDesc = "" +
	"\n" +
	"'notifications/proto/notifications.proto\x12\x10notifications.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n" +
	"\tRecipient\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x12!\n" +
	"\vbusiness_id\x18\x02 \x01(\tH\x00R\n" +
	"businessId\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\v \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"push_token\x18\f \x01(\tR\tpushTokenB\x04\n" +
	"\x02id\"\x8b\x03\n" +
	"\vSendRequest\x129\n" +
	"\trecipient\x18\x01 \x01(\v2\x1b.notifications.v1.RecipientR\trecipient\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12J\n" +
	"\tvariables\x18\x03 \x03(\v2,.notifications.v1.SendRequest.VariablesEntryR\tvariables\x126\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x1a.notifications.v1.CategoryR\bcategory\x125\n" +
	"\bchannels\x18\x05 \x03(\x0e2\x19.notifications.v1.ChannelR\bchannels\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\fSendResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x129\n" +
	"\aresults\x18\x02 \x03(\v2\x1f.notifications.v1.ChannelResultR\aresults\"\x96\x01\n" +
	"\rChannelResult\x123\n" +
	"\achannel\x18\x01 \x01(\x0e2\x19.notifications.v1.ChannelR\achannel\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .notifications.v1.DeliveryStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xc6\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x126\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x1a.notifications.v1.CategoryR\bcategory\x12\x12\n" +
	"\x04read\x18\x05 \x01(\bR\x04read\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\x04data\x18\a \x03(\v2(.notifications.v1.Notification.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x18ListNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\vunread_only\x18\x04 \x01(\bR\n" +
	"unreadOnly\"\x89\x01\n" +
	"\x19ListNotificationsResponse\x12D\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1e.notifications.v1.NotificationR\rnotifications\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"U\n" +
	"\x0fMarkReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10notification_ids\x18\x02 \x03(\tR\x0fnotificationIds\"7\n" +
	"\x10MarkReadResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\"0\n" +
	"\x15GetUnreadCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x91\x01\n" +
	"\x11ChannelPreference\x126\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1a.notifications.v1.CategoryR\bcategory\x12D\n" +
	"\x10enabled_channels\x18\x02 \x03(\x0e2\x19.notifications.v1.ChannelR\x0fenabledChannels\"y\n" +
	"\x17NotificationPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12E\n" +
	"\vpreferences\x18\x02 \x03(\v2#.notifications.v1.ChannelPreferenceR\vpreferences\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"z\n" +
	"\x18UpdatePreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12E\n" +
	"\vpreferences\x18\x02 \x03(\v2#.notifications.v1.ChannelPreferenceR\vpreferences*l\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCHANNEL_PUSH\x10\x01\x12\x0f\n" +
	"\vCHANNEL_SMS\x10\x02\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x03\x12\x12\n" +
	"\x0eCHANNEL_IN_APP\x10\x04*p\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CATEGORY_TRANSACTIONAL\x10\x01\x12\x18\n" +
	"\x14CATEGORY_PROMOTIONAL\x10\x02\x12\x14\n" +
	"\x10CATEGORY_ACCOUNT\x10\x03*\xa3\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DELIVERY_STATUS_QUEUED\x10\x01\x12\x18\n" +
	"\x14DELIVERY_STATUS_SENT\x10\x02\x12\x1e\n" +
	"\x1aDELIVERY_STATUS_SUPPRESSED\x10\x03\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\x042\xd4\x04\n" +
	"\x13NotificationService\x12E\n" +
	"\x04Send\x12\x1d.notifications.v1.SendRequest\x1a\x1e.notifications.v1.SendResponse\x12l\n" +
	"\x11ListNotifications\x12*.notifications.v1.ListNotificationsRequest\x1a+.notifications.v1.ListNotificationsResponse\x12Q\n" +
	"\bMarkRead\x12!.notifications.v1.MarkReadRequest\x1a\".notifications.v1.MarkReadResponse\x12c\n" +
	"\x0eGetUnreadCount\x12'.notifications.v1.GetUnreadCountRequest\x1a(.notifications.v1.GetUnreadCountResponse\x12d\n" +
	"\x0eGetPreferences\x12'.notifications.v1.GetPreferencesRequest\x1a).notifications.v1.NotificationPreferences\x12j\n" +
	"\x11UpdatePreferences\x12*.notifications.v1.UpdatePreferencesRequest\x1a).notifications.v1.NotificationPreferencesBDZBgithub.com/yourorg/grocery/gen/go/notifications/v1;notificationsv1b\x06proto3"

var (
	file_notifications_proto_notifications_proto_rawDescOnce sync.Once
	file_notifications_proto_notifications_proto_rawDescData []byte
)

func file_notifications_proto_notifications_proto_rawDescGZIP() []byte {
	file_notifications_proto_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_proto_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_proto_notifications_proto_rawDesc), len(file_notifications_proto_notifications_proto_rawDesc)))
	})
	return file_notifications_proto_notifications_proto_rawDescData
}

var file_notifications_proto_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_notifications_proto_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_notifications_proto_notifications_proto_goTypes = []any{
	(Channel)(0),                      // 0: notifications.v1.Channel
	(Category)(0),                     // 1: notifications.v1.Category
	(DeliveryStatus)(0),               // 2: notifications.v1.DeliveryStatus
	(*Recipient)(nil),                 // 3: notifications.v1.Recipient
	(*SendRequest)(nil),               // 4: notifications.v1.SendRequest
	(*SendResponse)(nil),              // 5: notifications.v1.SendResponse
	(*ChannelResult)(nil),             // 6: notifications.v1.ChannelResult
	(*Notification)(nil),              // 7: notifications.v1.Notification
	(*ListNotificationsRequest)(nil),  // 8: notifications.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil), // 9: notifications.v1.ListNotificationsResponse
	(*MarkReadRequest)(nil),           // 10: notifications.v1.MarkReadRequest
	(*MarkReadResponse)(nil),          // 11: notifications.v1.MarkReadResponse
	(*GetUnreadCountRequest)(nil),     // 12: notifications.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),    // 13: notifications.v1.GetUnreadCountResponse
	(*ChannelPreference)(nil),         // 14: notifications.v1.ChannelPreference
	(*NotificationPreferences)(nil),   // 15: notifications.v1.NotificationPreferences
	(*GetPreferencesRequest)(nil),     // 16: notifications.v1.GetPreferencesRequest
	(*UpdatePreferencesRequest)(nil),  // 17: notifications.v1.UpdatePreferencesRequest
	nil,                               // 18: notifications.v1.SendRequest.VariablesEntry
	nil,                               // 19: notifications.v1.Notification.DataEntry
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
}
var file_notifications_proto_notifications_proto_depIdxs = []int32{
	3,  // 0: notifications.v1.SendRequest.recipient:type_name -> notifications.v1.Recipient
	18, // 1: notifications.v1.SendRequest.variables:type_name -> notifications.v1.SendRequest.VariablesEntry
	1,  // 2: notifications.v1.SendRequest.category:type_name -> notifications.v1.Category
	0,  // 3: notifications.v1.SendRequest.channels:type_name -> notifications.v1.Channel
	6,  // 4: notifications.v1.SendResponse.results:type_name -> notifications.v1.ChannelResult
	0,  // 5: notifications.v1.ChannelResult.channel:type_name -> notifications.v1.Channel
	2,  // 6: notifications.v1.ChannelResult.status:type_name -> notifications.v1.DeliveryStatus
	1,  // 7: notifications.v1.Notification.category:type_name -> notifications.v1.Category
	20, // 8: notifications.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	19, // 9: notifications.v1.Notification.data:type_name -> notifications.v1.Notification.DataEntry
	7,  // 10: notifications.v1.ListNotificationsResponse.notifications:type_name -> notifications.v1.Notification
	1,  // 11: notifications.v1.ChannelPreference.category:type_name -> notifications.v1.Category
	0,  // 12: notifications.v1.ChannelPreference.enabled_channels:type_name -> notifications.v1.Channel
	14, // 13: notifications.v1.NotificationPreferences.preferences:type_name -> notifications.v1.ChannelPreference
	14, // 14: notifications.v1.UpdatePreferencesRequest.preferences:type_name -> notifications.v1.ChannelPreference
	4,  // 15: notifications.v1.NotificationService.Send:input_type -> notifications.v1.SendRequest
	8,  // 16: notifications.v1.NotificationService.ListNotifications:input_type -> notifications.v1.ListNotificationsRequest
	10, // 17: notifications.v1.NotificationService.MarkRead:input_type -> notifications.v1.MarkReadRequest
	12, // 18: notifications.v1.NotificationService.GetUnreadCount:input_type -> notifications.v1.GetUnreadCountRequest
	16, // 19: notifications.v1.NotificationService.GetPreferences:input_type -> notifications.v1.GetPreferencesRequest
	17, // 20: notifications.v1.NotificationService.UpdatePreferences:input_type -> notifications.v1.UpdatePreferencesRequest
	5,  // 21: notifications.v1.NotificationService.Send:output_type -> notifications.v1.SendResponse
	9,  // 22: notifications.v1.NotificationService.ListNotifications:output_type -> notifications.v1.ListNotificationsResponse
	11, // 23: notifications.v1.NotificationService.MarkRead:output_type -> notifications.v1.MarkReadResponse
	13, // 24: notifications.v1.NotificationService.GetUnreadCount:output_type -> notifications.v1.GetUnreadCountResponse
	15, // 25: notifications.v1.NotificationService.GetPreferences:output_type -> notifications.v1.NotificationPreferences
	15, // 26: notifications.v1.NotificationService.UpdatePreferences:output_type -> notifications.v1.NotificationPreferences
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_notifications_proto_notifications_proto_init() }
func file_notifications_proto_notifications_proto_init() {
	if File_notifications_proto_notifications_proto != nil {
		return
	}
	file_notifications_proto_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*Recipient_UserId)(nil),
		(*Recipient_BusinessId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_proto_notifications_proto_rawDesc), len(file_notifications_proto_notifications_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_proto_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_proto_notifications_proto_depIdxs,
		EnumInfos:         file_notifications_proto_notifications_proto_enumTypes,
		MessageInfos:      file_notifications_proto_notifications_proto_msgTypes,
	}.Build()
	File_notifications_proto_notifications_proto = out.File
	file_notifications_proto_notifications_proto_goTypes = nil
	file_notifications_proto_notifications_proto_depIdxs = nil
}
