app:
  name: product-service
  environment: development
  port: 8088

postgres:
  host: localhost
  port: 5439
  user: postgres
  password: postgres
  dbname: product_db
  sslmode: disable

grpc:
  port: 50060

jwt:
  public_key_path: ../../secrets/jwt_public.pem
  private_key_path: ../../secrets/jwt_private.pem
  access_token_ttl: 3600
