// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: inventory/proto/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockState int32

const (
	StockState_STOCK_STATE_UNSPECIFIED  StockState = 0
	StockState_STOCK_STATE_IN_STOCK     StockState = 1
	StockState_STOCK_STATE_LOW          StockState = 2 // at or below low_stock_threshold
	StockState_STOCK_STATE_OUT_OF_STOCK StockState = 3
	StockState_STOCK_STATE_DISCONTINUED StockState = 4
)

// Enum value maps for StockState.
var (
	StockState_name = map[int32]string{
		0: "STOCK_STATE_UNSPECIFIED",
		1: "STOCK_STATE_IN_STOCK",
		2: "STOCK_STATE_LOW",
		3: "STOCK_STATE_OUT_OF_STOCK",
		4: "STOCK_STATE_DISCONTINUED",
	}
	StockState_value = map[string]int32{
		"STOCK_STATE_UNSPECIFIED":  0,
		"STOCK_STATE_IN_STOCK":     1,
		"STOCK_STATE_LOW":          2,
		"STOCK_STATE_OUT_OF_STOCK": 3,
		"STOCK_STATE_DISCONTINUED": 4,
	}
)

func (x StockState) Enum() *StockState {
	p := new(StockState)
	*p = x
	return p
}

func (x StockState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StockState) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_proto_inventory_proto_enumTypes[0].Descriptor()
}

func (StockState) Type() protoreflect.EnumType {
	return &file_inventory_proto_inventory_proto_enumTypes[0]
}

func (x StockState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StockState.Descriptor instead.
func (StockState) EnumDescriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{0}
}

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_RESERVATION_STATUS_HELD        ReservationStatus = 1
	ReservationStatus_RESERVATION_STATUS_FAILED      ReservationStatus = 2 // insufficient stock on one or more lines
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "RESERVATION_STATUS_HELD",
		2: "RESERVATION_STATUS_FAILED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"RESERVATION_STATUS_HELD":        1,
		"RESERVATION_STATUS_FAILED":      2,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_proto_inventory_proto_enumTypes[1].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_inventory_proto_inventory_proto_enumTypes[1]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{1}
}

type AdjustmentReason int32

const (
	AdjustmentReason_ADJUSTMENT_REASON_UNSPECIFIED AdjustmentReason = 0
	AdjustmentReason_ADJUSTMENT_REASON_RESTOCK     AdjustmentReason = 1
	AdjustmentReason_ADJUSTMENT_REASON_SPOILAGE    AdjustmentReason = 2 // perishables expired or damaged
	AdjustmentReason_ADJUSTMENT_REASON_CORRECTION  AdjustmentReason = 3 // fix after a manual count
	AdjustmentReason_ADJUSTMENT_REASON_RETURN      AdjustmentReason = 4 // customer return back to shelf
	AdjustmentReason_ADJUSTMENT_REASON_STOCKTAKE   AdjustmentReason = 5 // full physical recount
)

// Enum value maps for AdjustmentReason.
var (
	AdjustmentReason_name = map[int32]string{
		0: "ADJUSTMENT_REASON_UNSPECIFIED",
		1: "ADJUSTMENT_REASON_RESTOCK",
		2: "ADJUSTMENT_REASON_SPOILAGE",
		3: "ADJUSTMENT_REASON_CORRECTION",
		4: "ADJUSTMENT_REASON_RETURN",
		5: "ADJUSTMENT_REASON_STOCKTAKE",
	}
	AdjustmentReason_value = map[string]int32{
		"ADJUSTMENT_REASON_UNSPECIFIED": 0,
		"ADJUSTMENT_REASON_RESTOCK":     1,
		"ADJUSTMENT_REASON_SPOILAGE":    2,
		"ADJUSTMENT_REASON_CORRECTION":  3,
		"ADJUSTMENT_REASON_RETURN":      4,
		"ADJUSTMENT_REASON_STOCKTAKE":   5,
	}
)

func (x AdjustmentReason) Enum() *AdjustmentReason {
	p := new(AdjustmentReason)
	*p = x
	return p
}

func (x AdjustmentReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdjustmentReason) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_proto_inventory_proto_enumTypes[2].Descriptor()
}

func (AdjustmentReason) Type() protoreflect.EnumType {
	return &file_inventory_proto_inventory_proto_enumTypes[2]
}

func (x AdjustmentReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdjustmentReason.Descriptor instead.
func (AdjustmentReason) EnumDescriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{2}
}

// A stock record is keyed by business + product + location. on_hand is the
// physical count; reserved is held by active reservations; available is the
// difference and is what customers can actually buy.
type StockItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BusinessId        string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	ProductId         string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`    // references the Products catalog
	LocationId        string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"` // "" for single-location businesses
	OnHand            int64                  `protobuf:"varint,4,opt,name=on_hand,json=onHand,proto3" json:"on_hand,omitempty"`            // physical units present
	Reserved          int64                  `protobuf:"varint,5,opt,name=reserved,proto3" json:"reserved,omitempty"`                      // units held by active reservations
	Available         int64                  `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`                    // derived: on_hand - reserved (returned for convenience)
	LowStockThreshold int64                  `protobuf:"varint,7,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"`
	State             StockState             `protobuf:"varint,8,opt,name=state,proto3,enum=inventory.v1.StockState" json:"state,omitempty"`
	// Optimistic-concurrency token. Pass it back on AdjustStock to avoid
	// clobbering a concurrent update. Stock is the most race-prone data you have.
	Version       string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *StockItem) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *StockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockItem) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *StockItem) GetOnHand() int64 {
	if x != nil {
		return x.OnHand
	}
	return 0
}

func (x *StockItem) GetReserved() int64 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *StockItem) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *StockItem) GetLowStockThreshold() int64 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

func (x *StockItem) GetState() StockState {
	if x != nil {
		return x.State
	}
	return StockState_STOCK_STATE_UNSPECIFIED
}

func (x *StockItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StockItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AvailabilityQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"` // how many the customer wants
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityQuery) Reset() {
	*x = AvailabilityQuery{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityQuery) ProtoMessage() {}

func (x *AvailabilityQuery) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityQuery.ProtoReflect.Descriptor instead.
func (*AvailabilityQuery) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *AvailabilityQuery) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *AvailabilityQuery) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AvailabilityQuery) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *AvailabilityQuery) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AvailabilityQuery   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAvailabilityRequest) GetItems() []*AvailabilityQuery {
	if x != nil {
		return x.Items
	}
	return nil
}

type AvailabilityResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Available     int64                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Sufficient    bool                   `protobuf:"varint,4,opt,name=sufficient,proto3" json:"sufficient,omitempty"` // available >= requested quantity
	State         StockState             `protobuf:"varint,5,opt,name=state,proto3,enum=inventory.v1.StockState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityResult) Reset() {
	*x = AvailabilityResult{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityResult) ProtoMessage() {}

func (x *AvailabilityResult) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityResult.ProtoReflect.Descriptor instead.
func (*AvailabilityResult) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *AvailabilityResult) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AvailabilityResult) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *AvailabilityResult) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *AvailabilityResult) GetSufficient() bool {
	if x != nil {
		return x.Sufficient
	}
	return false
}

func (x *AvailabilityResult) GetState() StockState {
	if x != nil {
		return x.State
	}
	return StockState_STOCK_STATE_UNSPECIFIED
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AvailabilityResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *CheckAvailabilityResponse) GetResults() []*AvailabilityResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReserveItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItem) Reset() {
	*x = ReserveItem{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItem) ProtoMessage() {}

func (x *ReserveItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItem.ProtoReflect.Descriptor instead.
func (*ReserveItem) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveItem) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *ReserveItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReserveItem) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ReserveItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // what the hold is for
	Items          []*ReserveItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Ttl            *durationpb.Duration   `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`                                             // hold auto-expires if not committed
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // retries/duplicate events must not double-hold
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveRequest) GetItems() []*ReserveItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *ReserveRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=inventory.v1.ReservationStatus" json:"status,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// On FAILED, lists the lines that couldn't be held so the caller can offer
	// substitutions or remove items.
	Shortfalls    []*AvailabilityResult `protobuf:"bytes,4,rep,name=shortfalls,proto3" json:"shortfalls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *ReserveResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ReserveResponse) GetShortfalls() []*AvailabilityResult {
	if x != nil {
		return x.Shortfalls
	}
	return nil
}

type CommitReservationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationId  string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitReservationRequest) Reset() {
	*x = CommitReservationRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReservationRequest) ProtoMessage() {}

func (x *CommitReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReservationRequest.ProtoReflect.Descriptor instead.
func (*CommitReservationRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *CommitReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CommitReservationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CommitReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     bool                   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReservationResponse) Reset() {
	*x = CommitReservationResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReservationResponse) ProtoMessage() {}

func (x *CommitReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReservationResponse.ProtoReflect.Descriptor instead.
func (*CommitReservationResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *CommitReservationResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // "cancelled", "payment_failed", "expired"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseReservationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseReservationResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type AdjustStockRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BusinessId string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	ProductId  string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	// Types that are valid to be assigned to Change:
	//
	//	*AdjustStockRequest_Delta
	//	*AdjustStockRequest_SetTo
	Change          isAdjustStockRequest_Change `protobuf_oneof:"change"`
	Reason          AdjustmentReason            `protobuf:"varint,6,opt,name=reason,proto3,enum=inventory.v1.AdjustmentReason" json:"reason,omitempty"`
	Note            string                      `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	ExpectedVersion string                      `protobuf:"bytes,8,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // optimistic-concurrency check (optional)
	IdempotencyKey  string                      `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdjustStockRequest) Reset() {
	*x = AdjustStockRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustStockRequest) ProtoMessage() {}

func (x *AdjustStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustStockRequest.ProtoReflect.Descriptor instead.
func (*AdjustStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *AdjustStockRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *AdjustStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AdjustStockRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *AdjustStockRequest) GetChange() isAdjustStockRequest_Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *AdjustStockRequest) GetDelta() int64 {
	if x != nil {
		if x, ok := x.Change.(*AdjustStockRequest_Delta); ok {
			return x.Delta
		}
	}
	return 0
}

func (x *AdjustStockRequest) GetSetTo() int64 {
	if x != nil {
		if x, ok := x.Change.(*AdjustStockRequest_SetTo); ok {
			return x.SetTo
		}
	}
	return 0
}

func (x *AdjustStockRequest) GetReason() AdjustmentReason {
	if x != nil {
		return x.Reason
	}
	return AdjustmentReason_ADJUSTMENT_REASON_UNSPECIFIED
}

func (x *AdjustStockRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AdjustStockRequest) GetExpectedVersion() string {
	if x != nil {
		return x.ExpectedVersion
	}
	return ""
}

func (x *AdjustStockRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type isAdjustStockRequest_Change interface {
	isAdjustStockRequest_Change()
}

type AdjustStockRequest_Delta struct {
	Delta int64 `protobuf:"varint,4,opt,name=delta,proto3,oneof"` // relative: +50 restock, -3 spoilage
}

type AdjustStockRequest_SetTo struct {
	SetTo int64 `protobuf:"varint,5,opt,name=set_to,json=setTo,proto3,oneof"` // absolute: result of a physical count
}

func (*AdjustStockRequest_Delta) isAdjustStockRequest_Change() {}

func (*AdjustStockRequest_SetTo) isAdjustStockRequest_Change() {}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *GetStockRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *GetStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetStockRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type ListStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`                                  // optional filter
	StateFilter   StockState             `protobuf:"varint,3,opt,name=state_filter,json=stateFilter,proto3,enum=inventory.v1.StockState" json:"state_filter,omitempty"` // optional, e.g. only LOW / OUT_OF_STOCK
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStockRequest) Reset() {
	*x = ListStockRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStockRequest) ProtoMessage() {}

func (x *ListStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStockRequest.ProtoReflect.Descriptor instead.
func (*ListStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *ListStockRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *ListStockRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ListStockRequest) GetStateFilter() StockState {
	if x != nil {
		return x.StateFilter
	}
	return StockState_STOCK_STATE_UNSPECIFIED
}

func (x *ListStockRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStockRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStockResponse) Reset() {
	*x = ListStockResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStockResponse) ProtoMessage() {}

func (x *ListStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStockResponse.ProtoReflect.Descriptor instead.
func (*ListStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *ListStockResponse) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListStockResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_inventory_proto_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1finventory/proto/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xf4\x02\n" +
	"\tStockItem\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x17\n" +
	"\aon_hand\x18\x04 \x01(\x03R\x06onHand\x12\x1a\n" +
	"\breserved\x18\x05 \x01(\x03R\breserved\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\x03R\tavailable\x12.\n" +
	"\x13low_stock_threshold\x18\a \x01(\x03R\x11lowStockThreshold\x12.\n" +
	"\x05state\x18\b \x01(\x0e2\x18.inventory.v1.StockStateR\x05state\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x01\n" +
	"\x11AvailabilityQuery\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"Q\n" +
	"\x18CheckAvailabilityRequest\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.inventory.v1.AvailabilityQueryR\x05items\"\xc2\x01\n" +
	"\x12AvailabilityResult\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x03R\tavailable\x12\x1e\n" +
	"\n" +
	"sufficient\x18\x04 \x01(\bR\n" +
	"sufficient\x12.\n" +
	"\x05state\x18\x05 \x01(\x0e2\x18.inventory.v1.StockStateR\x05state\"W\n" +
	"\x19CheckAvailabilityResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .inventory.v1.AvailabilityResultR\aresults\"\x8a\x01\n" +
	"\vReserveItem\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\xb2\x01\n" +
	"\x0eReserveRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.inventory.v1.ReserveItemR\x05items\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\xee\x01\n" +
	"\x0fReserveResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.inventory.v1.ReservationStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12@\n" +
	"\n" +
	"shortfalls\x18\x04 \x03(\v2 .inventory.v1.AvailabilityResultR\n" +
	"shortfalls\"j\n" +
	"\x18CommitReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"9\n" +
	"\x19CommitReservationResponse\x12\x1c\n" +
	"\tcommitted\x18\x01 \x01(\bR\tcommitted\"Z\n" +
	"\x19ReleaseReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"8\n" +
	"\x1aReleaseReservationResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"\xd0\x02\n" +
	"\x12AdjustStockRequest\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x16\n" +
	"\x05delta\x18\x04 \x01(\x03H\x00R\x05delta\x12\x17\n" +
	"\x06set_to\x18\x05 \x01(\x03H\x00R\x05setTo\x126\n" +
	"\x06reason\x18\x06 \x01(\x0e2\x1e.inventory.v1.AdjustmentReasonR\x06reason\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x12)\n" +
	"\x10expected_version\x18\b \x01(\tR\x0fexpectedVersion\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKeyB\b\n" +
	"\x06change\"r\n" +
	"\x0fGetStockRequest\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\"\xcd\x01\n" +
	"\x10ListStockRequest\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\tR\n" +
	"businessId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12;\n" +
	"\fstate_filter\x18\x03 \x01(\x0e2\x18.inventory.v1.StockStateR\vstateFilter\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"j\n" +
	"\x11ListStockResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.inventory.v1.StockItemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\x94\x01\n" +
	"\n" +
	"StockState\x12\x1b\n" +
	"\x17STOCK_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STOCK_STATE_IN_STOCK\x10\x01\x12\x13\n" +
	"\x0fSTOCK_STATE_LOW\x10\x02\x12\x1c\n" +
	"\x18STOCK_STATE_OUT_OF_STOCK\x10\x03\x12\x1c\n" +
	"\x18STOCK_STATE_DISCONTINUED\x10\x04*s\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RESERVATION_STATUS_HELD\x10\x01\x12\x1d\n" +
	"\x19RESERVATION_STATUS_FAILED\x10\x02*\xd5\x01\n" +
	"\x10AdjustmentReason\x12!\n" +
	"\x1dADJUSTMENT_REASON_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ADJUSTMENT_REASON_RESTOCK\x10\x01\x12\x1e\n" +
	"\x1aADJUSTMENT_REASON_SPOILAGE\x10\x02\x12 \n" +
	"\x1cADJUSTMENT_REASON_CORRECTION\x10\x03\x12\x1c\n" +
	"\x18ADJUSTMENT_REASON_RETURN\x10\x04\x12\x1f\n" +
	"\x1bADJUSTMENT_REASON_STOCKTAKE\x10\x052\xeb\x04\n" +
	"\x10InventoryService\x12d\n" +
	"\x11CheckAvailability\x12&.inventory.v1.CheckAvailabilityRequest\x1a'.inventory.v1.CheckAvailabilityResponse\x12B\n" +
	"\bGetStock\x12\x1d.inventory.v1.GetStockRequest\x1a\x17.inventory.v1.StockItem\x12F\n" +
	"\aReserve\x12\x1c.inventory.v1.ReserveRequest\x1a\x1d.inventory.v1.ReserveResponse\x12d\n" +
	"\x11CommitReservation\x12&.inventory.v1.CommitReservationRequest\x1a'.inventory.v1.CommitReservationResponse\x12g\n" +
	"\x12ReleaseReservation\x12'.inventory.v1.ReleaseReservationRequest\x1a(.inventory.v1.ReleaseReservationResponse\x12H\n" +
	"\vAdjustStock\x12 .inventory.v1.AdjustStockRequest\x1a\x17.inventory.v1.StockItem\x12L\n" +
	"\tListStock\x12\x1e.inventory.v1.ListStockRequest\x1a\x1f.inventory.v1.ListStockResponseB<Z:github.com/yourorg/grocery/gen/go/inventory/v1;inventoryv1b\x06proto3"

var (
	file_inventory_proto_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_inventory_proto_rawDescData []byte
)

func file_inventory_proto_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_inventory_proto_rawDesc), len(file_inventory_proto_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_inventory_proto_rawDescData
}

var file_inventory_proto_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_inventory_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_inventory_proto_inventory_proto_goTypes = []any{
	(StockState)(0),                    // 0: inventory.v1.StockState
	(ReservationStatus)(0),             // 1: inventory.v1.ReservationStatus
	(AdjustmentReason)(0),              // 2: inventory.v1.AdjustmentReason
	(*StockItem)(nil),                  // 3: inventory.v1.StockItem
	(*AvailabilityQuery)(nil),          // 4: inventory.v1.AvailabilityQuery
	(*CheckAvailabilityRequest)(nil),   // 5: inventory.v1.CheckAvailabilityRequest
	(*AvailabilityResult)(nil),         // 6: inventory.v1.AvailabilityResult
	(*CheckAvailabilityResponse)(nil),  // 7: inventory.v1.CheckAvailabilityResponse
	(*ReserveItem)(nil),                // 8: inventory.v1.ReserveItem
	(*ReserveRequest)(nil),             // 9: inventory.v1.ReserveRequest
	(*ReserveResponse)(nil),            // 10: inventory.v1.ReserveResponse
	(*CommitReservationRequest)(nil),   // 11: inventory.v1.CommitReservationRequest
	(*CommitReservationResponse)(nil),  // 12: inventory.v1.CommitReservationResponse
	(*ReleaseReservationRequest)(nil),  // 13: inventory.v1.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil), // 14: inventory.v1.ReleaseReservationResponse
	(*AdjustStockRequest)(nil),         // 15: inventory.v1.AdjustStockRequest
	(*GetStockRequest)(nil),            // 16: inventory.v1.GetStockRequest
	(*ListStockRequest)(nil),           // 17: inventory.v1.ListStockRequest
	(*ListStockResponse)(nil),          // 18: inventory.v1.ListStockResponse
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 20: google.protobuf.Duration
}
var file_inventory_proto_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.StockItem.state:type_name -> inventory.v1.StockState
	19, // 1: inventory.v1.StockItem.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 2: inventory.v1.CheckAvailabilityRequest.items:type_name -> inventory.v1.AvailabilityQuery
	0,  // 3: inventory.v1.AvailabilityResult.state:type_name -> inventory.v1.StockState
	6,  // 4: inventory.v1.CheckAvailabilityResponse.results:type_name -> inventory.v1.AvailabilityResult
	8,  // 5: inventory.v1.ReserveRequest.items:type_name -> inventory.v1.ReserveItem
	20, // 6: inventory.v1.ReserveRequest.ttl:type_name -> google.protobuf.Duration
	1,  // 7: inventory.v1.ReserveResponse.status:type_name -> inventory.v1.ReservationStatus
	19, // 8: inventory.v1.ReserveResponse.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 9: inventory.v1.ReserveResponse.shortfalls:type_name -> inventory.v1.AvailabilityResult
	2,  // 10: inventory.v1.AdjustStockRequest.reason:type_name -> inventory.v1.AdjustmentReason
	0,  // 11: inventory.v1.ListStockRequest.state_filter:type_name -> inventory.v1.StockState
	3,  // 12: inventory.v1.ListStockResponse.items:type_name -> inventory.v1.StockItem
	5,  // 13: inventory.v1.InventoryService.CheckAvailability:input_type -> inventory.v1.CheckAvailabilityRequest
	16, // 14: inventory.v1.InventoryService.GetStock:input_type -> inventory.v1.GetStockRequest
	9,  // 15: inventory.v1.InventoryService.Reserve:input_type -> inventory.v1.ReserveRequest
	11, // 16: inventory.v1.InventoryService.CommitReservation:input_type -> inventory.v1.CommitReservationRequest
	13, // 17: inventory.v1.InventoryService.ReleaseReservation:input_type -> inventory.v1.ReleaseReservationRequest
	15, // 18: inventory.v1.InventoryService.AdjustStock:input_type -> inventory.v1.AdjustStockRequest
	17, // 19: inventory.v1.InventoryService.ListStock:input_type -> inventory.v1.ListStockRequest
	7,  // 20: inventory.v1.InventoryService.CheckAvailability:output_type -> inventory.v1.CheckAvailabilityResponse
	3,  // 21: inventory.v1.InventoryService.GetStock:output_type -> inventory.v1.StockItem
	10, // 22: inventory.v1.InventoryService.Reserve:output_type -> inventory.v1.ReserveResponse
	12, // 23: inventory.v1.InventoryService.CommitReservation:output_type -> inventory.v1.CommitReservationResponse
	14, // 24: inventory.v1.InventoryService.ReleaseReservation:output_type -> inventory.v1.ReleaseReservationResponse
	3,  // 25: inventory.v1.InventoryService.AdjustStock:output_type -> inventory.v1.StockItem
	18, // 26: inventory.v1.InventoryService.ListStock:output_type -> inventory.v1.ListStockResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_inventory_proto_inventory_proto_init() }
func file_inventory_proto_inventory_proto_init() {
	if File_inventory_proto_inventory_proto != nil {
		return
	}
	file_inventory_proto_inventory_proto_msgTypes[12].OneofWrappers = []any{
		(*AdjustStockRequest_Delta)(nil),
		(*AdjustStockRequest_SetTo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_inventory_proto_rawDesc), len(file_inventory_proto_inventory_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_proto_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_proto_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto_inventory_proto = out.File
	file_inventory_proto_inventory_proto_goTypes = nil
	file_inventory_proto_inventory_proto_depIdxs = nil
}
